name: Test and Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r code/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest code/tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          mkdir -p logs
          docker build --progress=plain -f code/Dockerfile -t ai-data-engineer-assignment:latest . 2>&1 | tee logs/Docker_build.txt

      - name: List Docker images
        run: docker images

      - name: Save pip list to logs
        run: |
          mkdir -p logs
          docker run --rm ai-data-engineer-assignment:latest pip list > logs/pip_list.txt
