name: Test and Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r code/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest code/tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -f code/Dockerfile -t ai-data-engineer-assignment:latest . | tee docker_build.log

      - name: List Docker images
        run: docker images

      - name: Save Docker build log
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-log
          path: docker_build.log

      - name: Save pip list
        run: |
          docker run --rm ai-data-engineer-assignment:latest pip list > pip_list.txt

      - name: Upload pip list
        uses: actions/upload-artifact@v4
        with:
          name: pip-list
          path: pip_list.txt