name: Test and Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r code/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest code/tests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          mkdir -p logs
          docker build --progress=plain -f code/Dockerfile -t ai-data-engineer-assignment:latest . 2>&1 | tee logs/Docker_build.txt

      - name: List Docker images
        run: docker images

      - name: Save Docker build log
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-log
          path: logs/Docker_build.txt

      - name: Save pip list
        run: |
          mkdir -p logs
          docker run --rm ai-data-engineer-assignment:latest pip list > logs/pip_list.txt

      - name: Upload pip list
        uses: actions/upload-artifact@v4
        with:
          name: pip-list
          path: logs/pip_list.txt

      - name: Process specific words
        run: |
          mkdir -p logs
          docker run --rm -v $PWD/logs:/app/logs ai-data-engineer-assignment:latest \
            python /app/src/run.py process_data --cfg config/cfg.yaml -dataset news --dirout ztmp/data

      - name: Process all words
        run: |
          mkdir -p logs
          docker run --rm -v $PWD/logs:/app/logs ai-data-engineer-assignment:latest \
            python /app/src/run.py process_data_all --cfg config/cfg.yaml -dataset news --dirout ztmp/data

      - name: Upload data processed logs
        uses: actions/upload-artifact@v4
        with:
          name: data-processed-logs
          path: logs/Data_processed*.txt

      - name: Commit and push logs
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add logs/Docker_build.txt
          git add logs/pip_list.txt
          git add logs/Data_processed.txt
          git add logs/Data_processed_all.txt
          git commit -m 'Add pip list, docker build logs, data processed logs'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}